Тест test_error завершился с ОШИБКОЙ: Произошла ошибка
Тест test_failure завершился с НЕУДАЧЕЙ: 1 != 2
Тест test_success УСПЕШНО выполнен
